import { ImagePlus, Music2, Save, Trash2, Upload } from "lucide-react";
import { useState, type FormEvent } from "react";
import { useNavigate } from "@tanstack/react-router";
import type { Song } from "@/lib/songs";
import { Button, Panel } from "./ui";
export function SongForm({song,onDelete}:{song?:Song;onDelete?:()=>void}){
 const navigate=useNavigate(); const [errors,setErrors]=useState<Record<string,string>>({}); const [preview,setPreview]=useState(song?.artwork); const [saved,setSaved]=useState(false);
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);const next:Record<string,string>={};if(!data.get("title"))next.title="Song name is required";if(!data.get("artist"))next.artist="Artist name is required";if(!data.get("lyrics"))next.lyrics="Add lyrics or song content";setErrors(next);if(Object.keys(next).length===0){setSaved(true);setTimeout(()=>navigate({to:"/songs"}),900)}}
 function fileChange(file?:File){if(file){const reader=new FileReader();reader.onload=()=>typeof reader.result==="string"&&setPreview(reader.result);reader.readAsDataURL(file)}}
 return <form onSubmit={submit} className="form-layout"><div className="form-main"><Panel><div className="panel-title"><Music2/><div><h2>Song identity</h2><p>Core catalog and publishing information.</p></div></div><div className="form-grid"><Field label="Song name" required error={errors.title}><input name="title" defaultValue={song?.title} placeholder="e.g. Midnight Echoes"/></Field><Field label="Artist name" required error={errors.artist}><input name="artist" defaultValue={song?.artist} placeholder="e.g. Luna Vale"/></Field><Field label="Album / release"><input name="album" defaultValue={song?.album} placeholder="Album or single name"/></Field><Field label="Genre"><select name="genre" defaultValue={song?.genre??"Alternative Pop"}><option>Alternative Pop</option><option>Electronic</option><option>Indie Folk</option><option>Acoustic</option></select></Field><Field label="Language"><select name="language" defaultValue={song?.language??"English"}><option>English</option><option>Hindi</option><option>Spanish</option><option>French</option></select></Field><Field label="Catalog status"><select name="status" defaultValue={song?.status??"Draft"}><option>Published</option><option>Draft</option><option>Review</option></select></Field></div></Panel><Panel><div className="panel-title"><Music2/><div><h2>Lyrics & content</h2><p>Format lyrics with one line per phrase.</p></div></div><Field label="Lyrics / song content" required error={errors.lyrics}><textarea name="lyrics" rows={12} defaultValue={song?.lyrics} placeholder="Enter song lyrics here..."/></Field></Panel></div><aside className="form-aside"><Panel><div className="panel-title"><ImagePlus/><div><h2>Cover artwork</h2><p>Square JPG, PNG or WebP.</p></div></div><label className="upload-zone">{preview?<img src={preview} alt="Cover preview"/>:<><Upload/><strong>Upload cover artwork</strong><small>Recommended 1200 × 1200px</small></>}<input type="file" accept="image/*" onChange={e=>fileChange(e.target.files?.[0])}/></label></Panel><Panel><h2 className="section-title">Publishing</h2><label className="switch-row"><div><strong>Public visibility</strong><small>Show this song on the website</small></div><input type="checkbox" defaultChecked={song?.status==="Published"}/></label><label className="switch-row"><div><strong>Featured release</strong><small>Highlight across catalog views</small></div><input type="checkbox"/></label></Panel>{onDelete&&<Panel className="danger-panel"><h2 className="section-title">Danger zone</h2><p>Deleting this song permanently removes its catalog record.</p><Button variant="danger" onClick={onDelete}><Trash2/> Delete song</Button></Panel>}</aside><div className="form-actions"><Button variant="secondary" onClick={()=>history.back()}>Cancel</Button><Button type="submit"><Save/>{saved?"Saved":"Save song"}</Button></div></form>
}
function Field({label,required,error,children}:{label:string;required?:boolean;error?:string;children:React.ReactNode}){return <label className={`field ${error?"field-error":""}`}><span>{label}{required&&<b>*</b>}</span>{children}{error&&<small>{error}</small>}</label>}
